/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package guii;

import dao.CurriculumDao;
import dao.QualificationDao;
import gui.component.CurriculumTableModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import poo.Curriculum;
import poo.Qualification;

/**
 *
 * @author shady
 */
public class CurriculoCadastro extends javax.swing.JInternalFrame {

    private Curriculum curriculum = null;
    private CurriculumDao curriculumDao = new CurriculumDao();
    private DefaultListModel listaQ = new DefaultListModel();
    
    /** Creates new form CurriculoCadastro */
    public CurriculoCadastro() {
        initComponents();
        

        loadComboQualification();
        enableForm(false);
//        loadTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtApresentation = new javax.swing.JTextArea();
        cb_Qualification = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        qList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btnAddQ = new keeptoo.KButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txtGoal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cbNascionalidade = new javax.swing.JComboBox<>();
        btnRemoveQ = new keeptoo.KButton();
        btSalvar = new keeptoo.KButton();
        btNovo = new keeptoo.KButton();
        btCancelar = new keeptoo.KButton();
        btExcluir = new keeptoo.KButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro de Curriculo");

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkTransparentControls(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome Completo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apresentação");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Qualificações: ");

        txtApresentation.setColumns(20);
        txtApresentation.setRows(5);
        jScrollPane1.setViewportView(txtApresentation);

        cb_Qualification.setEditable(true);

        jScrollPane2.setViewportView(qList);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");

        btnAddQ.setText("Adicionar");
        btnAddQ.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddQ.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btnAddQ.setkHoverForeGround(new java.awt.Color(153, 153, 153));
        btnAddQ.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        btnAddQ.setkSelectedColor(new java.awt.Color(153, 153, 153));
        btnAddQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQActionPerformed(evt);
            }
        });

        jTable1.setModel(new CurriculumTableModel());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Idade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Objetivo:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Celular:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nacionalidade:");

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        cbNascionalidade.setEditable(true);
        cbNascionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brasileiro", "Afegão", "Africano", "Alemão", "Americano", "Argentino", "Asiático", "Australiano", "Austríaco", "Belga", "Britânico", "Canadense", "Chileno", "Chinês", "Colombiano", "Coreano", "Croata", "Dinamarquês", "Egípcio", "Escocês", "Eslovaco", "Espanhol", "Europeu", "Filipino", "Finlandês", "Francesa", "Francês", "Francês", "Grego", "Holandês", "Indiano", "Inglês", "Iraniano", "Iraquiano", "Italiano", "Japonês", "Mexicano", "Norueguês", "Paquistanês", "Polonês", "Português", "Russo", "Sueco", "Sul-Africano", "Sul-Coreano", "Turco", "Árabe" }));

        btnRemoveQ.setText("Remover");
        btnRemoveQ.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRemoveQ.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btnRemoveQ.setkHoverForeGround(new java.awt.Color(153, 153, 153));
        btnRemoveQ.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        btnRemoveQ.setkSelectedColor(new java.awt.Color(153, 153, 153));
        btnRemoveQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cb_Qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAddQ, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(btnRemoveQ, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addGap(28, 28, 28)
                                    .addComponent(txtEmail))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbNascionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cbNascionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cb_Qualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddQ, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveQ, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        btSalvar.setText("Salvar");
        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btSalvar.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btSalvar.setkHoverForeGround(new java.awt.Color(153, 153, 153));
        btSalvar.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        btSalvar.setkSelectedColor(new java.awt.Color(153, 153, 153));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btNovo.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btNovo.setkHoverForeGround(new java.awt.Color(153, 153, 153));
        btNovo.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        btNovo.setkSelectedColor(new java.awt.Color(153, 153, 153));
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btCancelar.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btCancelar.setkHoverForeGround(new java.awt.Color(153, 153, 153));
        btCancelar.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        btCancelar.setkSelectedColor(new java.awt.Color(153, 153, 153));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btExcluir.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btExcluir.setkHoverForeGround(new java.awt.Color(153, 153, 153));
        btExcluir.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        btExcluir.setkSelectedColor(new java.awt.Color(153, 153, 153));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        curriculum = new Curriculum();
        //chama o método habilitar formulario ativando os botoes
        enableForm(true);
        btExcluir.setEnabled(false);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (formValidate()) {
            

            curriculum.setFullName(txtName.getText().trim());
            curriculum.setEmail(txtEmail.getText());
            curriculum.setCelular(txtCelular.getText());
            curriculum.setNacionalidade(cbNascionalidade.getSelectedItem().toString());
            curriculum.setIdade((Integer) jSpinner1.getValue());
            curriculum.setObjetivo(txtGoal.getText());
                    
            curriculum.setPresentation(txtApresentation.getText());
            
            curriculum.setQualifications(new ArrayList<Qualification>());
            
            
            for (int i = 0; i < qList.getModel().getSize(); i++) {
                Qualification q = (Qualification) qList.getModel().getElementAt(i);
                curriculum.setQualifications(q);
            }
            
            if(curriculum.getId() == 0){
                try{
                    curriculumDao.insert(curriculum);
                    JOptionPane.showMessageDialog(this, "Sua Curriculo Foi Cadastrado"
                    , "Concluido", JOptionPane.INFORMATION_MESSAGE);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this, "Erro ao inserir Cadastro."
                    + "\n" +ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                try{
                    curriculumDao.update(curriculum);
                    JOptionPane.showMessageDialog(this, "Seu Curriculo Foi Cadastrado"
                    , "Concluido", JOptionPane.INFORMATION_MESSAGE);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this, "Erro ao alterar Cadastro."
                    + "\n" +ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        loadTable(curriculum.getEmail());
        enableForm(false);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        enableForm(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btnAddQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQActionPerformed
        
        Qualification qualificationCb = (Qualification) cb_Qualification.getSelectedItem();
        
        if (listValidation(qualificationCb)) {
            listaQ.addElement(qualificationCb);
            qList.setModel(listaQ);
        }
        
    }//GEN-LAST:event_btnAddQActionPerformed
    
    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        try{
            curriculumDao.delete(curriculum);
            loadTable(txtEmail.getText());
            enableForm(false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao Exluir."
                    + "\n" +ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){

            CurriculumTableModel tm = (CurriculumTableModel) jTable1.getModel();

            curriculum = tm.getRowValue(jTable1.getSelectedRow());

            txtName.setText(curriculum.getFullName());
            txtEmail.setText(curriculum.getEmail());
            txtCelular.setText(curriculum.getCelular());
            txtGoal.setText(curriculum.getObjetivo());
            cbNascionalidade.setSelectedItem(curriculum.getNacionalidade());
            txtApresentation.setText(curriculum.getPresentation());
            listLoad(curriculum.getQualifications());

            enableForm(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        loadTable(txtEmail.getText());
        if (jTable1.getRowCount() > 0) {
            JOptionPane.showMessageDialog(this, "Esse email ja foi cadastrado, você pode Continuar ou cancelar e editar seu curriculum anterior"
                    , "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnRemoveQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveQActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) qList.getModel();
        int selectedIndex = qList.getSelectedIndex();
        if (selectedIndex != -1) {
            model.remove(selectedIndex);
        }
    }//GEN-LAST:event_btnRemoveQActionPerformed

    
     private void listLoad(ArrayList<Qualification> q){
         
         listaQ.clear();
         for (Qualification q1 : q) {
            
            Qualification qualificationCb = (Qualification) q1;
            listaQ.addElement(qualificationCb);
            qList.setModel(listaQ);
         }
    }
    
    
    private boolean listValidation (Qualification qualificationCb){
        
        for (int i = 0; i < qList.getModel().getSize(); i++) {
            Qualification q = (Qualification) qList.getModel().getElementAt(i);
            String interation = q.getQualificationName();
            String newQ = qualificationCb.getQualificationName();
            if (interation.equals(newQ) ) {
                return false;
            }
        }
        return true;
    }
    
    private void enableForm(boolean ativo){
        btNovo.setEnabled(!ativo);
        btSalvar.setEnabled(ativo);
        btExcluir.setEnabled(ativo);
        btCancelar.setEnabled(ativo);
        txtName.setEnabled(ativo);
        txtEmail.setEnabled(ativo);
        txtCelular.setEnabled(ativo);
        txtApresentation.setEnabled(ativo);
        txtGoal.setEnabled(ativo);
        cbNascionalidade.setEnabled(ativo);
        cb_Qualification.setEnabled(ativo);
        jSpinner1.setEnabled(ativo);
        btnAddQ.setEnabled(ativo);
        //btnSearch.setEnabled(ativo);
        //jTable1.setEnabled(!ativo);
        
        if(!ativo){
            clearForm();
        }
    }
    
    private void clearForm (){
        txtName.setText("");
        txtEmail.setText("");
        txtCelular.setText("");
        txtApresentation.setText("");
        txtGoal.setText("");
        jSpinner1.setValue(0);
        listaQ.clear();
        
        
        
    }
    
     private void loadComboQualification(){
        
        QualificationDao qualificaitonDao = new QualificationDao();
        ArrayList<Qualification> qualificationList = new ArrayList<Qualification>();

        try{
            qualificationList = qualificaitonDao.listAll();
            
            for (Qualification q : qualificationList) {
                cb_Qualification.addItem(q);
            };
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao carregar Qualificações."
                    + "\n" +ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private boolean formValidate(){
        if(txtName.getText().trim().length() < 2){
            JOptionPane.showMessageDialog(this, "Nome inválido", "Alerta",
            JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(txtEmail.getText().trim().length() < 2){
            JOptionPane.showMessageDialog(this, "Email inválido", "Alerta",
            JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(txtApresentation.getText().trim().length() < 2){
            JOptionPane.showMessageDialog(this, "Apresentação Invalida", "Alerta",
            JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }
     
     private void loadTable(String email){
        CurriculumTableModel tm = (CurriculumTableModel) jTable1.getModel();
        
        try{
            tm.setDados(curriculumDao.GetByEmail(email));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao carregar a grade."
                    + "\n" +ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btCancelar;
    private keeptoo.KButton btExcluir;
    private keeptoo.KButton btNovo;
    private keeptoo.KButton btSalvar;
    private keeptoo.KButton btnAddQ;
    private keeptoo.KButton btnRemoveQ;
    private javax.swing.JComboBox<String> cbNascionalidade;
    private javax.swing.JComboBox<Object> cb_Qualification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JList<Object> qList;
    private javax.swing.JTextArea txtApresentation;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGoal;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
