/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guii;

/**
 *
 * @author shady
 */
public class FormacaoProfissional extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormacaoProfissional
     */
    public FormacaoProfissional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btSalvar = new keeptoo.KButton();
        txtRegiaoInteresse = new javax.swing.JTextField();
        jtxtFormacaoAcademica = new javax.swing.JTextField();
        lblRegiaoDeInteresse = new javax.swing.JLabel();
        txtPretencaoSalarial = new javax.swing.JTextField();
        txtAreaInteresse = new javax.swing.JTextField();
        lblAreasDeInteresse = new javax.swing.JLabel();
        lblPretencaoSalarial = new javax.swing.JLabel();
        lblObjetivoProfissional = new javax.swing.JLabel();
        txtObjetivoProfissional = new javax.swing.JTextField();
        lblObjetivos = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblInformacaoDeContato = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtNascionalidade = new javax.swing.JTextField();
        lblNascionalidade = new javax.swing.JLabel();
        lblFilhos = new javax.swing.JLabel();
        txtFilhos = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblResumoProfissional = new javax.swing.JLabel();
        jtxtResumoProfissional = new javax.swing.JTextField();
        lblFormacaoAcademica = new javax.swing.JLabel();

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));

        btSalvar.setText("Salvar");
        btSalvar.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btSalvar.setkHoverForeGround(new java.awt.Color(153, 153, 153));
        btSalvar.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        btSalvar.setkSelectedColor(new java.awt.Color(153, 153, 153));

        lblRegiaoDeInteresse.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblRegiaoDeInteresse.setForeground(new java.awt.Color(255, 255, 255));
        lblRegiaoDeInteresse.setText("Região de Interesse: ");

        lblAreasDeInteresse.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblAreasDeInteresse.setForeground(new java.awt.Color(255, 255, 255));
        lblAreasDeInteresse.setText("Áreas de interesse: ");

        lblPretencaoSalarial.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblPretencaoSalarial.setForeground(new java.awt.Color(255, 255, 255));
        lblPretencaoSalarial.setText("Pretenção Salarial: ");

        lblObjetivoProfissional.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblObjetivoProfissional.setForeground(new java.awt.Color(255, 255, 255));
        lblObjetivoProfissional.setText("Objetivo Profissional: ");

        lblObjetivos.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblObjetivos.setForeground(new java.awt.Color(204, 255, 204));
        lblObjetivos.setText("Objetivos");

        lblCelular.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular.setText("Celular: ");

        lblTelefone.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setText("Telefone: ");

        lblEmail.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail: ");

        lblInformacaoDeContato.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblInformacaoDeContato.setForeground(new java.awt.Color(204, 255, 204));
        lblInformacaoDeContato.setText("Informações de Contato");

        lblEndereco.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço: ");

        lblDocumento.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblDocumento.setForeground(new java.awt.Color(255, 255, 255));
        lblDocumento.setText("Documento: ");

        lblNascionalidade.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblNascionalidade.setForeground(new java.awt.Color(255, 255, 255));
        lblNascionalidade.setText("Nascionalidade: ");

        lblFilhos.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblFilhos.setForeground(new java.awt.Color(255, 255, 255));
        lblFilhos.setText("Possui filhos:");

        lblIdade.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(255, 255, 255));
        lblIdade.setText("Idade : ");

        lblNome.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 255, 204));
        lblNome.setText("Nome ");

        lblResumoProfissional.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblResumoProfissional.setForeground(new java.awt.Color(204, 255, 204));
        lblResumoProfissional.setText("Resumo Profissional");

        lblFormacaoAcademica.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblFormacaoAcademica.setForeground(new java.awt.Color(204, 255, 204));
        lblFormacaoAcademica.setText("Formação Ácademica");
        lblFormacaoAcademica.setToolTipText("");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdade))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblFilhos)
                        .addGap(1, 1, 1)
                        .addComponent(txtFilhos))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblNascionalidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNascionalidade))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocumento))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblObjetivoProfissional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObjetivoProfissional))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblAreasDeInteresse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAreaInteresse))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblRegiaoDeInteresse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegiaoInteresse))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInformacaoDeContato)
                            .addComponent(lblObjetivos)
                            .addComponent(lblNome))
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblPretencaoSalarial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretencaoSalarial)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormacaoAcademica)
                    .addComponent(jtxtResumoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResumoProfissional)
                    .addComponent(jtxtFormacaoAcademica, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(lblResumoProfissional))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtResumoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdade)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFilhos)
                            .addComponent(txtFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNascionalidade)
                            .addComponent(txtNascionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocumento)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEndereco)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblInformacaoDeContato)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFormacaoAcademica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCelular)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblObjetivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblObjetivoProfissional)
                            .addComponent(txtObjetivoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAreasDeInteresse)
                            .addComponent(txtAreaInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPretencaoSalarial)
                            .addComponent(txtPretencaoSalarial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegiaoInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegiaoDeInteresse))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtxtFormacaoAcademica))
                .addGap(37, 37, 37)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btSalvar;
    private javax.swing.JTextField jtxtFormacaoAcademica;
    private javax.swing.JTextField jtxtResumoProfissional;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblAreasDeInteresse;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFilhos;
    private javax.swing.JLabel lblFormacaoAcademica;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblInformacaoDeContato;
    private javax.swing.JLabel lblNascionalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObjetivoProfissional;
    private javax.swing.JLabel lblObjetivos;
    private javax.swing.JLabel lblPretencaoSalarial;
    private javax.swing.JLabel lblRegiaoDeInteresse;
    private javax.swing.JLabel lblResumoProfissional;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtAreaInteresse;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFilhos;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNascionalidade;
    private javax.swing.JTextField txtObjetivoProfissional;
    private javax.swing.JTextField txtPretencaoSalarial;
    private javax.swing.JTextField txtRegiaoInteresse;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
